FROM oven/bun:1.1.42-alpine

WORKDIR /app

COPY package.json bun.lockb tsconfig.base.json ./
COPY apps/frontend/package.json apps/frontend/package.json
COPY packages/universe/package.json packages/universe/package.json
RUN bun install --frozen-lockfile

COPY apps/frontend apps/frontend
COPY packages/universe packages/universe

WORKDIR /app/apps/frontend
RUN bun run build:test

ENV NODE_ENV=production
ENV PORT=80

CMD ["bun", "run", "serve"]
