FROM oven/bun:1.2.4-alpine

WORKDIR /app

COPY package.json bun.lockb tsconfig.base.json ./
COPY apps apps
COPY packages packages

RUN bun install --frozen-lockfile

WORKDIR /app/apps/frontend
RUN bun run build:test

ENV NODE_ENV=production
ENV PORT=80

CMD ["bun", "run", "serve"]
