/**
 * Image size utilities for Veydrift responsive asset delivery.
 *
 * Generates srcset strings for game assets that have build-time size
 * variants under /assets/game/sizes/<width>/.
 */

/** Canonical variant widths generated by the build script. */
export const VARIANT_WIDTHS = [64, 256, 512] as const;

/** Width of the original full-size game assets (verified: all current assets are 1024×1024,
 *  except the 2K high-res ship at 2048×2048). */
export const ORIGINAL_WIDTH = 1024;

/** Special-case width for known high-res assets. */
const HIGH_RES_WIDTH = 2048;

/**
 * Build a srcset string for an original game asset path.
 *
 * Example:
 *   getSrcSet("/assets/game/planets/lush-temperate.webp")
 *   // => "/assets/game/sizes/64/planets/lush-temperate.webp 64w, ... 1024w"
 */
export function getSrcSet(originalSrc: string): string {
  const variants = VARIANT_WIDTHS.map((w) => {
    const path = originalSrc.replace("/assets/game/", `/assets/game/sizes/${w}/`);
    return `${path} ${w}w`;
  });

  const originalWidth = originalSrc.includes("2k") || originalSrc.includes("high-res")
    ? HIGH_RES_WIDTH
    : ORIGINAL_WIDTH;

  return [...variants, `${originalSrc} ${originalWidth}w`].join(", ");
}

/**
 * Predefined `sizes` attribute values for common UI layouts.
 * These describe the rendered slot width so the browser can pick
 * the optimal srcset candidate.
 */
export const Sizes = {
  /** Fixed 40×40 icon (GalaxyView planet thumbnails). */
  icon: "40px",

  /** Shipyard ship thumbnail: 128×80 mobile, 160×96 on sm+. */
  shipThumbnail: "(min-width: 640px) 160px, 128px",

  /** Infrastructure card: 1-col mobile, 2-col sm, 3-col lg. Image is w-full. */
  buildingCard: "(min-width: 1024px) 33vw, (min-width: 640px) 50vw, 100vw",

  /** Research card: 1-col mobile, 2-col sm. Image is w-full. */
  researchCard: "(min-width: 640px) 50vw, 100vw",

  /** Planet detail: 300px fixed on lg+, full-width below. */
  planetPreview: "(min-width: 1024px) 300px, 100vw",

  /** Full-width hero image (OverviewPage planet banner). */
  hero: "100vw",
} as const;

/** Type-safe size preset names. */
export type SizePreset = keyof typeof Sizes;
