FROM oven/bun:1.2.4-alpine

WORKDIR /app

COPY package.json bun.lockb tsconfig.base.json ./
COPY apps apps
COPY packages packages

RUN bun install --frozen-lockfile

WORKDIR /app/apps/backend
RUN bun run build

ENV NODE_ENV=production
ENV PORT=4000

CMD ["bun", "run", "start"]
